### PR TITLE
Adding subgraph post function and fixing the conformance test code

### PR DESCRIPTION
**Pull request by kellrott**
User can now add entire subgraph to graph in one post. Example in `conformance/tests/ot_graphpost.py`. Also fixes a number of bugs in the conformance test package.

### CODE REVIEW

**Comment by buchanae** [comment]
What is a subgraph?

**Comment by kellrott** [comment]
I called it a subgraph, because it is a complete graph, but it gets appended to another graph, rather then replacing it.

**Comment by buchanae** [comment]
Since it's not a new entity, yet it seems like one, I think this can be improved. Also, what is `EditResult.id` when `AddSubgraph` is called?

**Comment by buchanae** [comment]
Or, just a general `AddElements` and drop almost everything else? Not a blocker, but this seems like the right time to figure out the best concepts. It's not going to change easily later.

**Comment by kellrott** [comment]
Do you want to take a pass on aql.proto ?

**Comment by buchanae** [comment]
Sure. Do you want to split out the unrelated fix in this PR? Or just wait?

**Comment by kellrott** [comment]
Lets just merge this for now, and work on revisions later.

**Pull request merged**
